### ISSUE TITLE
Inspect memory unreal

### ISSUE THREAD

**Issue by mmar22** [platformio/platform-espressif32#1119]
What kind of issue is this?

bad Inspect memory results or good but dont SPIRAM info?

**PlatformIO Version** (`platformio --version`): 3.2.0

### Description of problem
Explain this results 
![image](https://github.com/platformio/platformio-core/assets/11925350/81d2d7fd-992a-4e55-978d-c4fada306b47)

**Comment by valeros** [comment]
Hi @mmar22 

As you may know, there are three regions of RAM in espressif32 mcu: `DRAM, IRAM, D/IRAM` (it's also possible to use an external IC as DRAM). The memory usage report after a simple compilation is parsed by the following regex:
```
    SIZEPROGREGEXP=r"^(?:\.iram0\.text|\.iram0\.vectors|\.dram0\.data|\.flash\.text|\.flash\.rodata|)\s+([0-9]+).*",
    SIZEDATAREGEXP=r"^(?:\.dram0\.data|\.dram0\.bss|\.noinit)\s+([0-9]+).*",
```
As you can see, `.iram0.text` section is attributed to `PROGRAM`, nonetheless it's still RAM, but yes, it's used for storing executable data. In board manifests, you can see `"maximum_ram_size": 327680`, `327680` is the size of DRAM region and it's done on purpose, because DRAM is the main R/W RAM region used for stack, heap, static variables, etc. When the Project Inspector analyzes your firmware, it doesn't known about these limitations, it's simply looks at each symbol in your firmware and then decides which section it belongs to. 

If you think it's wrong, then simply adjust RAM size in your `platformio.ini` file.
