### ISSUE TITLE
ESP32-C3 crashes when using `printf(float)` when compiled with PlatformIO

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif32#1189]
Using IDF 5.1.1 with latest Pio Platform `platform = espressif32 @ ^6.4.0`
This [example](https://github.com/Jason2866/espidf-test_float) crashes with the C3.
Same example run on a C6 does work.

Compiling and running the same example with native IDF release 5.1.1 does work as expected on all tested MCUs (ESP32, ESP32-S2, ESP32-S3, ESP32-C2, ESP32-C3 and ESP32-C6)

**Comment by valeros** [comment]
Hi @Jason2866, many thanks for reporting! Turns out there was a broken toolchain package for RISC-V targets, although it interesting how the toolchain silently concealed this problem. Anyway, proper packages have been uploaded to the registry with the same version, so please remove the old one `v12.2.0+20230208` somewhere here `~/.platformio/packages/toolchain-riscv32-esp` and run your project again.
