### ISSUE TITLE
Inability to compile for TTGO T-Watch ESP32

### ISSUE THREAD

**Issue by DiegoG1019** [platformio/platform-espressif32#519]
![image](https://user-images.githubusercontent.com/61756479/112700439-8ab62a00-8e64-11eb-80d8-873082111fa3.png)
I am unable to compile any project for this platform (haven't tested other platforms) as it always gives me this error -- despite the files in question being there, names and directories checked

My full project is [here (latest code is in develop branch)](https://github.com/DiegoG1019/LilyGo-DGWatch)
I also tried building [this one here](https://github.com/sharandac/My-TTGO-Watch) for the same effect

The steps to reproduce the error are, in my machine, simply pressing the build and upload / verify button
I'm using the platformio extension on VSCode
![image](https://user-images.githubusercontent.com/61756479/112701799-f8b02080-8e67-11eb-901c-4b40a66b9448.png)

![image](https://user-images.githubusercontent.com/61756479/112701821-0c5b8700-8e68-11eb-9ca3-6d75af922451.png)
Platformio.ini

**Comment by valeros** [comment]
Hi @DiegoG1019 ! It looks like a problem with the `TTGO TWatch Library` library not with PlatformIO. Instead of proper declaration of dependencies the maintainers of `TTGO TWatch Library` library decided to dump all dependencies in the `library` folder and use relative include paths.  I'd recommend you to download `TTGO TWatch Library` to your `lib` folder and modify the `library.json` file in the following manner:
```json
{
    "name": "TTGO TWatch Library",
    "keywords": "Device Conterl,TWatch,Watch,TTGO",
    "description": "Arduino Library for LilyGo T-Watch & LilyPi & T-Block development kit",
    "repository": {
        "type": "git",
        "url": "https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git"
    },
    "authors": [
        {
            "name": "Xinyuan Electronics",
            "email": "lily@lilygo.cc",
            "url": "https://github.com/Xinyuan-LilyGO",
            "maintainer": true
        }
    ],
    "version": "1.4.2",
    "frameworks": "arduino",
    "platforms": "esp32",
    "build": {
        "flags": [
            "-Isrc",
            "-Isrc/libraries/TFT_eSPI/Fonts/GFXFF",
            "-Isrc/libraries/TFT_eSPI/User_Setups"
        ]
    }
}
```
If it works you might also consider submitting a PR to the upstream `TTGO TWatch Library` repository.
