### ISSUE TITLE
Requesting Support For MicroMod ESP32 Board

### ISSUE THREAD

**Issue by toneware** [platformio/platform-espressif32#521]
Please look at supporting the Sparkfun Micomod esp32 processor board.

From https://www.sparkfun.com/products/16781 : 

ESP32 General Features:
Dual-core Tensilica LX6 microprocessor
Up to 240MHz clock frequency
520kB internal SRAM
128mbit/16MB flash storage

**Comment by seanhagen** [comment]
I think I got it working?

Using the [board config URL from the SparkFun ESP32 MicroMod software setup guide](https://learn.sparkfun.com/tutorials/micromod-esp32-processor-board-hookup-guide/software-setup-and-programming), I took the [.tar.bz2 from that JSON file](https://github.com/sparkfun/Arduino_Boards/raw/main/IDE_Board_Manager/sparkfun-esp32-1.0.1.tar.bz2) and did two things:

1. Copied the `variants/esp32micromod` to `~/.platformio/packages/framework-arduinoespressif32/variants` so that I had the `pins_arduino.h` file
2. Forked platformio/platform-espressif32 and added the [esp32micromod.json to the `boards` folder](https://github.com/seanhagen/platform-espressif32/blob/add-sparkfun-esp32-micromod/boards/esp32micromod.json) 

Then once I set up my `platformio.ini` file like so:

```ini
[env:esp32micromod]
platform = https://github.com/seanhagen/platform-espressif32.git#add-sparkfun-esp32-micromod
board = esp32micromod
framework = arduino
```

It compiles and uploads and runs!

I can't find the repo that `pio` downloads when it downloads the `framework-arduinoespressif32` framework, so I wasn't able to fork that to add `esp32micromod/pins_arduino.h`  to it, but I have created a [pr for the platformio-espressif32](https://github.com/platformio/platform-espressif32/pull/605) repo to add the JSON
