### ISSUE TITLE
ESP32-S3 timeline?

### ISSUE THREAD

**Issue by dskulina** [platformio/platform-espressif32#650]
Do you have a timeline for the addition of the ESP32-S3 board?

**Comment by AndyW999** [comment]
I have some ESP32-S3-DEVKITC-1 arriving soon and it would be nice to be able to use them...

**Comment by jonathandreyer** [comment]
Hi everyone,

I have started the porting of ESP32-S3 in PlatformIO (with ESP-IDF v4.4-beta). You can find more information [here](https://github.com/platformio/platform-espressif32/issues/674#issuecomment-1008337065).

Best regards,

Jonathan Dreyer

**Comment by jonathandreyer** [comment]
@ivankravets @valeros Maybe we can close it? From my side, I have tested the `develop` branch with the ESP32-S3-DEVKITC-1 and that work fine. I have an interrogation with the `flash_size`, `maximum_ram_size` & `maximum_size`, because the embedded module has 8MB of flash (or more). The table with this information can be viewed [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html#contents-and-packaging).
Best regards,
Jonathan
