### ISSUE TITLE
ESP32 ULP Build does not follow CMakeLists

### ISSUE THREAD

**Issue by DocWibbleyWobbley** [platformio/platform-espressif32#940]
When building a project the ULP program is always built from all `.S` files in `ulp` folder and is always named `ulp_main`.
When building the same project with IDF-ESP the CMakeLists.txt is obeyed properly.
Therefore it's not possible to configure different ULP programs based on component configuration.
More info in this [PlatformIO discussion](https://community.platformio.org/t/esp32-ulp-build-does-not-follow-cmakelists/29987)

**Comment by Jason2866** [comment]
The behaviour is as designed and as described in Platformio documentation.

**Comment by DocWibbleyWobbley** [comment]
Can you provide a link to said documentation?
I seem to be unable to find anything about that.
I tried with the [Registry](https://registry.platformio.org/platforms/platformio/espressif32), [Documentation](https://docs.platformio.org/en/latest/platforms/espressif32.html), and looked in both ulp examples.

**Comment by valeros** [comment]
Hi @DocWibbleyWobbley ! @Jason2866 is right, although it's not documented. Currently, all source files are collected from the `ulp` folder, mainly because the underlying IDF build system doesn't export necessary information to reproduce the build logic to the full extent.

**Comment by Jason2866** [comment]
The structure is described https://docs.platformio.org/en/latest/frameworks/espidf.html#ulp-coprocessor-programming

**Comment by DocWibbleyWobbley** [comment]
@valeros I see
@Jason2866 Thanks

**Comment by m-mcgowan** [comment]
Not being able to use libraries, lack of support of multiple ULP images and the constant conflict between Espressifs CMake-base documentation vs what was implemented forced me to implement a more capable solution which aims to solve these problems "by design". 

`pio-ulp-cmake` uses the unmodified IDF cmake files, with information provided to SCons for correct dependency resolution for incremental builds.  It supports multiple ULP binaries, each with an optional prefix in the generated header symbols to avoid clashes.  It's tested against recent pioarduino versions and successfully builds various IDF ULP examples without modification, targeting several espressif MCUs with FSM, ULP and LP core coprocessors.

Integration is little more than adding it as a dependency, and setting:

```
lib_deps =
    https://github.com/m-mcgowan/pio-ulp-cmake.git

extra_scripts =
    pre:${PROJECT_LIBDEPS_DIR}/${PIOENV}/pio-ulp-cmake/scripts/pio_ulp_cmake.py
```

Then define the location(s) of your ulp directories, ulp name, and symbol prefix.

```
board_build.ulp_projects =
# name:dir[:prefix]
    ulp_main:ulp
    ulp_sensor:ulp_sensor:sensor_
```

More details in the repo - https://github.com/m-mcgowan/pio-ulp-cmake.

**Comment by Jason2866** [comment]
@m-mcgowan  https://github.com/m-mcgowan/pio-ulp-cmake  -> 404 ?!

**Comment by m-mcgowan** [comment]
Fixed.
